### ISSUE TITLE
Root-FS issue with 05-UpgradeInstall.sh

### ISSUE THREAD

**Issue by wespo** [ToolChainGang/AppDaemon#1]
Running the installer, it assumes my filesystem is unexpanded, despite the fact that there is plenty of space.

```root@UNIAC-003:~/AppDaemon/install# ./05-UpgradeInstall.sh
Disk  : 64021856256
Part1 : 2346223104
Part2 : 1024
Unused: 61675632128
============>Disk is not expanded, automatically expanding with reboot...

for some reason, it thinks unused is less than 500000000...
=========================
Upgrading linux```

I think line 84 of `05-UpgradeInstall.sh` should be `-lt` instead of `-gt`. Also, the file system expansion fails.

Additionally, `raspi-config --expand-rootfs` fails anyway with an error saying that the filesystem is already expanded, but this check prevents the install from completing. Commenting out the check allows the installation to continue.

**Comment by ToolChainGang** [comment]
The code appears correct, but the comments are misleading. I'll fix the 
comments presently.

I think the problem arises because you're using a 64GB card, and it 
might be overflowing the numeric checks in raspi-config. I need to 
purchase a 64GB card to test this, it will take a couple of days and 
I'll report back.

The if statement is testing the amount of space *not* taken up by the 
two partitions. If the system is not expanded that will be a large 
amount, and your info shows 61G so since this is >0.5G the OS should be 
expanded. I think the if is correct.

The fact that the raspi-config fails the expansion is the root cause. It 
should expand correctly once, then the 2nd time the unused space will be 
less than 0.5G and the boot continued.

This is a do-once step for your development, so it shouldn't hold you 
back. You might verify that your disk is expanded using gparted (gui) or 
parted (command line) - from the numbers it appears that you have 61GB 
unpartitioned.

--Pete

**Comment by ToolChainGang** [comment]
Comments changed for better clarity.
The program should not be automatically expanding the disk - that's fine for my workflow, but not appropriate in general.
I've removed the automatic disk expansion, it instead exits (without reboot) and prints the expansion command.
I still think the math in raspi-config is overflowing, but that's a separate issue on a different product.
